### PR TITLE
Add min parameter

### PR DESCRIPTION
**Pull request by s-simoncelli**

### CODE REVIEW

**Review by jetuk — CHANGES_REQUESTED** [review]
This looks good to me. A couple of suggestions if you have time:

- Rebase this branch against master.
- Implement: `impl TryFromV1Parameter<MinParameterV1> for MinParameter`.

We should add docstrings to the schemas as well, but I need to agree a format for these first.

**Comment by s-simoncelli** [comment]
I have opened a new [pull request ](https://github.com/pywr/pywr-schema/pull/11)on the schema project. Once that's approved I'll implement `TryFromV1Parameter`.

Let me know when you've decided abotu the docstring and I'll update the code. Do I need to add a docstring to the parameter as well?

**Comment by jetuk** [comment]
> I have opened a new [pull request ](https://github.com/pywr/pywr-schema/pull/11)on the schema project. Once that's approved I'll implement `TryFromV1Parameter`.

Thanks I've merged this.

> Let me know when you've decided abotu the docstring and I'll update the code. Do I need to add a docstring to the parameter as well?

I think we should probably just follow this format: https://doc.rust-lang.org/rust-by-example/meta/doc.html

**Comment by s-simoncelli** [comment]
I added the docstring to the schema, let me know if it's OK.

I also need to pull the new changes from the schema repository, but there is no new version. Can you please push a new tag so that I can update the `Cargo.toml` file and implement the parameter conversion?

Cheers

**Review by jetuk — APPROVED** [review]

**Pull request merged**
