### PR TITLE
feat: Add additional COIN-OR bindings for Cbc.

### PR DESCRIPTION
**Pull request by jetuk**
This requires adding Cgl and Osi libraries. Currently these are vendored in the same way as Clp. This is an alternative to #207 which seems to have build / linking issues. The longer term plan would be to move this -sys package to separate repository and remove the submodules from here. We'll keep it here for now while we develop the CBC solver and integer variables.

### CODE REVIEW

**Review by Batch21 — APPROVED** [review]
works for me

**Comment by jetuk** [comment]
Shall I add an initial CBC solver implementation here, or do that in another PR?

**Comment by Batch21** [comment]
> Shall I add an initial CBC solver implementation here, or do that in another PR?

Happy either way. Would be cleaner in a new PR unless you think the implementation might required modifying the changes in this PR?

**Comment by jetuk** [comment]
I do not think it will.

One issue I have immediately found is that the CBC C interface has no method for modifying matrix coefficients (unlike CLP).

**Pull request merged**
