### PR TITLE
feat: Add RbfProfileParameter

### PR DESCRIPTION
**Pull request by jetuk**
This is an initial implementation of RbfProfile parameter. It uses a basic RBF interpolation procedure.

It has the following missing features:

- [ ] Implementation of `TryFromV1Parameter`.
- [x] Implementation of `VariableParameter`.

### CODE REVIEW

**Review by Batch21 — APPROVED** [review]
Had a read through this and it all looks good

**Comment by jetuk** [comment]
Do we want to merge this without the implementation of `TryFromV1Parameter`? That's dependent on merging https://github.com/pywr/pywr-schema/pull/16

**Comment by Batch21** [comment]
> Do we want to merge this without the implementation of `TryFromV1Parameter`? That's dependent on merging [pywr/pywr-schema#16](https://github.com/pywr/pywr-schema/pull/16)

sorry, I missed that PR. Just had a look and approved it. Probably better to implement `TryFromV1Parameter` here?

**Comment by jetuk** [comment]
This is now waiting on #66

**Comment by Batch21** [comment]
I haven't test the `TryFromV1Parameter` implementation but it looks like it should work

**Pull request merged**
